#!/usr/bin/env bash
set -euo pipefail

export PIPERS_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${DOTFILES}/scripts/core/main.sh"

main() {
    cd "${PIPERS_HOME}"
    rm "${PIPERS_HOME}/wasm/lib.rs.bk" &>/dev/null || true
    cp "${PIPERS_HOME}/wasm/src/lib.rs" "${PIPERS_HOME}/wasm/lib.rs.bk"
    rm -rf "${PIPERS_HOME}/wasm/src" 
    cp -r "${PIPERS_HOME}/src" "${PIPERS_HOME}/wasm/src"
    rm "${PIPERS_HOME}/wasm/src/lib.rs"
    mv "${PIPERS_HOME}/wasm/lib.rs.bk" "${PIPERS_HOME}/wasm/src/lib.rs"
    rm -rf "${PIPERS_HOME}/wasm/src/bin"

    cd "${PIPERS_HOME}/wasm"
    wasm-pack build # --target web

    rm -rf "${PIPERS_HOME}/web/pkg" &>/dev/null || true
}

main "$@"