#!/usr/bin/env bash
set -euo pipefail

export PIPERS_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${DOTFILES}/scripts/core/main.sh"

main() {
    "${PIPERS_HOME}/scripts/build-wasm"

    cd "${PIPERS_HOME}/web"
    yarn install 
    yarn run deploy
}

main "$@"
