#!/usr/bin/env bash
set -euo pipefail

export PIPERS_HOME="$(cd "$(dirname "$0")/.." && pwd)"
source "${DOTFILES}/scripts/core/main.sh"

main() {
    if ! [ -f "${PIPERS_HOME}/wasm/pkg/pipers.js" ]; then
        "${PIPERS_HOME}/scripts/build-wasm"
    fi
    
    rm -rf "${PIPERS_HOME}/web/node_modules/pipers" &>/dev/null || true
    mv "${PIPERS_HOME}/wasm/pkg" "${PIPERS_HOME}/web/pkg"
    cp -r "${PIPERS_HOME}/web/pkg" "${PIPERS_HOME}/web/node_modules/pipers"

    cd "${PIPERS_HOME}/web"
    yarn install 
    yarn start
}

main "$@"